# Generated by Django 4.2.7 on 2023-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('Lastname', models.CharField(max_length=225)),
                ('number', models.CharField(max_length=225)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('Lastname', models.CharField(max_length=225)),
                ('number', models.CharField(max_length=225)),
                ('specialization', models.CharField(blank=True, max_length=225, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
